<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreQuestionRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }
    public function  messages()
    {
        return [
            'title.required'=>'Title can not empty.',
            'title.min'=>'Title must more than 6 char.',
            'body.required'=>'Description can not empty.',
            'body.min'=>'Description must more than 26 char.',
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {

        return [
            'title'=>'required|min:6|max:196',
            'body'=>'required|min:26',
        ];
    }
}
